apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
    containerImage: harbor.pue.es/oraclepdo/pueteam/oracle-pdb-operator:0.0.8
    createdAt: 2021-10-29T11:59:59Z
    description: An operator to create Oracle PDBs
    repository: https://github.com/pueteam/oracle-pdb-operator
    alm-examples: |-
      [
        {
          "apiVersion": "oracle.pue.es/v1alpha1",
          "kind": "pdb",
          "metadata": {
            "name": "oracle-pdb",
            "namespace": "oracle"
          },
          "spec": {
            "storage": 1000000000,
            "tempStorage": 10000000,
            "adminName": pdbadmin,
            "adminPwd": W3lc0m31
          }
        }
      ]
  name: oracle-pdb-operator.v0.0.8
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Oracle PDB Operator
      kind: pdb 
      name: pdbs.oracle.pue.es
      version: v1alpha1
  description: Operator for Oracle PDBs.
  displayName: Oracle PDB Operator
  icon:
    - base64data: "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTguNTEgMjU4LjUxIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2QxZDFkMTt9LmNscy0ye2ZpbGw6IzhkOGQ4Zjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkFzc2V0IDQ8L3RpdGxlPjxnIGlkPSJMYXllcl8yIiBkYXRhLW5hbWU9IkxheWVyIDIiPjxnIGlkPSJMYXllcl8xLTIiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMTI5LjI1LDIwQTEwOS4xLDEwOS4xLDAsMCwxLDIwNi40LDIwNi40LDEwOS4xLDEwOS4xLDAsMSwxLDUyLjExLDUyLjExLDEwOC40NSwxMDguNDUsMCwwLDEsMTI5LjI1LDIwbTAtMjBoMEM1OC4xNiwwLDAsNTguMTYsMCwxMjkuMjVIMGMwLDcxLjA5LDU4LjE2LDEyOS4yNiwxMjkuMjUsMTI5LjI2aDBjNzEuMDksMCwxMjkuMjYtNTguMTcsMTI5LjI2LTEyOS4yNmgwQzI1OC41MSw1OC4xNiwyMDAuMzQsMCwxMjkuMjUsMFoiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xNzcuNTQsMTAzLjQxSDE0MS42NkwxNTQuOSw2NS43NmMxLjI1LTQuNC0yLjMzLTguNzYtNy4yMS04Ljc2SDEwMi45M2E3LjMyLDcuMzIsMCwwLDAtNy40LDZsLTEwLDY5LjYxYy0uNTksNC4xNywyLjg5LDcuODksNy40LDcuODloMzYuOUwxMTUuNTUsMTk3Yy0xLjEyLDQuNDEsMi40OCw4LjU1LDcuMjQsOC41NWE3LjU4LDcuNTgsMCwwLDAsNi40Ny0zLjQ4TDE4NCwxMTMuODVDMTg2Ljg2LDEwOS4yNCwxODMuMjksMTAzLjQxLDE3Ny41NCwxMDMuNDFaIi8+PC9nPjwvZz48L3N2Zz4="
      mediatype: "image/svg+xml"
  install:
    spec:
      deployments:
      - name: oracle-pdb-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: oracle-pdb-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: oracle-pdb-operator
            spec:
              containers:
              - name: oracle-pdb-operator
                env:
                - name: CRD
                  value: "true"
                - name: ORDS_HOST
                  value: "oracle-db-ords-service"
                - name: ORDS_PORT
                  value: "8888"
                - name: ORDS_PROTOCOL
                  value: "http"
                - name: ORDS_USER
                  valueFrom:
                    secretKeyRef:
                      name: oracle-db-ords-credentials
                      key: username
                - name: ORDS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: oracle-db-ords-credentials
                      key: password
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: oracle-pdb-operator
                image: harbor.pue.es/oraclepdo/pueteam/oracle-pdb-operator:0.0.8
                imagePullPolicy: Always
                resources: {}
              serviceAccountName: oracle-pdb-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - oracle-pdb-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - oracle.pue.es
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: oracle-pdb-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - memcached
  - app
  maintainers:
  - email: sergio@pue.es
    name: PUE Data
  maturity: alpha
  provider:
    name: PUE
    url: www.pue.es
  version: 0.0.8
  minKubeVersion: 1.20.0
