apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: oracle-pdb-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: harbor.pue.es/oraclepdo/pueteam/oracle-pdb-catalog:latest
