apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-db-data
  namespace: oracle
spec:
  # storageClassName: oci
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi